import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    // apps/desktop is a separate Cargo workspace (rustfmt-owned), and its CHANGELOG plus the
    // release-please manifest are generated by release-please — keep Oxfmt out of them, or it
    // reformats release-please's output and fails `check` on every release PR.
    ignorePatterns: ["apps/desktop/**", ".release-please-manifest.json"],
  },
  lint: { options: { typeAware: true, typeCheck: true } },
});
